### ISSUE TITLE
problem with next-mdx-remote doesn't pass the component

### ISSUE THREAD

**Issue by mxcdh** [kjmczk/nextjs-mdx-food-blog#2]
Hello

I have error: 'TypeError: Cannot read properties of undefined (reading 'map')'.

I understand what this error means.
But I still understand, why ingredients.array is not available in my components.
I transmit array from .mdx files.

Bellow my project (whole blog):
https://stackblitz.com/edit/nextjs-cbqaq9?file=components%2FIngredients.tsx

**Comment by kjmczk** [comment]
Use React Context instead of passing props to the components.

**Comment by mxcdh** [comment]
@kjmczk  thanks for response.
I added context, this same as in your repository, but i still have this same error:
https://stackblitz.com/edit/nextjs-cbqaq9?file=context%2FMdxComponents.tsx

Can you help me?

**Comment by kjmczk** [comment]
Use `useMdxComponentsContext()` in the Directions and Tips components as well as the Ingredients component.
If you get a "Cannot read properties of undefined" error, use the `?` operator: `ingredients?.map()`

**Comment by mxcdh** [comment]
Hi, 

If I use "ingredients?.map()" I have always empty object.
Maybe code in useMdxComponentsContext is wrong?

**Comment by kjmczk** [comment]
That might be the case. Please review the code again to find the problem.
